<?php
$modversion['name'] = _MI_MYADDRESSES_NAME;
$modversion['version'] = 1.720081112;
$modversion['author'] = "Rota Lucio + Shine aka Triangle";
$modversion['description'] = _MI_MYADDRESSES_DESC;
$modversion['credits'] = " Kazumi Ono - The XOOPS Project\nhttp://www.mywebaddons.com/";
$modversion['help'] = "addresses.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "images/addresses_slogo.png";
$modversion['dirname'] = "addresses";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "addresses_cat";
$modversion['tables'][1] = "addresses_cat_text";
$modversion['tables'][2] = "addresses_addresses";
$modversion['tables'][3] = "addresses_addresses_text";
$modversion['tables'][4] = "addresses_mod";
$modversion['tables'][5] = "addresses_broken";
$modversion['tables'][6] = "addresses_votedata";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks
$modversion['blocks'][1]['file'] = "addresses_top.php";
$modversion['blocks'][1]['name'] = _MI_MYADDRESSES_BNAME1;
$modversion['blocks'][1]['description'] = _MI_MYADDRESSES_BDESC1;
$modversion['blocks'][1]['show_func'] = "b_addresses_top_show";
$modversion['blocks'][1]['edit_func'] = "b_addresses_top_edit";
$modversion['blocks'][1]['options'] = "date|10|25";
$modversion['blocks'][1]['template'] = 'addresses_block_new.html';

$modversion['blocks'][2]['file'] = "addresses_top.php";
$modversion['blocks'][2]['name'] = _MI_MYADDRESSES_BNAME2;
$modversion['blocks'][2]['description'] = _MI_MYADDRESSES_BDESC2;
$modversion['blocks'][2]['show_func'] = "b_addresses_top_show";
$modversion['blocks'][2]['edit_func'] = "b_addresses_top_edit";
$modversion['blocks'][2]['options'] = "hits|10|25";
$modversion['blocks'][2]['template'] = 'addresses_block_top.html';

//  2007/07/31 by luciorota - start
$modversion['blocks'][3]['file'] = "addresses_categories.php";
$modversion['blocks'][3]['name'] = _MI_MYADDRESSES_BNAME3;
$modversion['blocks'][3]['description'] = _MI_MYADDRESSES_BDESC3;
$modversion['blocks'][3]['show_func'] = "b_addresses_categories_show";
$modversion['blocks'][3]['edit_func'] = "b_addresses_categories_edit"; 
$modversion['blocks'][3]['options'] = "25";
$modversion['blocks'][3]['template'] = 'addresses_block_categories.html';
//  2007/07/31 by luciorota - end

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_MYADDRESSES_SMNAME1;
$modversion['sub'][1]['url'] = "address_submit.php";
$modversion['sub'][2]['name'] = _MI_MYADDRESSES_SMNAME2;
$modversion['sub'][2]['url'] = "topten.php?hit=1";
$modversion['sub'][3]['name'] = _MI_MYADDRESSES_SMNAME3;
$modversion['sub'][3]['url'] = "topten.php?rate=1";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "addresses_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'aid';
$modversion['comments']['pageName'] = 'address_single.php';
$modversion['comments']['extraParams'] = array('cid');
// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'addresses_com_approve';
$modversion['comments']['callback']['update'] = 'addresses_com_update';

// Templates. If adding extra templates adjust/submit here
$modversion['templates'][1]['file'] = 'addresses_brokenaddress.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'addresses_address.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'addresses_index.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'addresses_modaddress.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'addresses_rateaddress.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'addresses_singleaddress.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = 'addresses_submit.html';
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = 'addresses_topten.html';
$modversion['templates'][8]['description'] = '';
$modversion['templates'][9]['file'] = 'addresses_viewcat.html';
$modversion['templates'][9]['description'] = '';
$modversion['templates'][10]['file'] = 'addresses_viewaddress.html';
$modversion['templates'][10]['description'] = '';
$modversion['templates'][11]['file'] = 'addresses_google_maps.html';
$modversion['templates'][11]['description'] = '';

// Config Settings (only for modules that need config settings generated automatically)
$i=1;
// name of config option for accessing its specified value. i.e. $xoopsModuleConfig['storyhome']
$modversion['config'][$i]['name'] = 'popular';
// title of this config option displayed in config settings form
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_POPULAR';
// description of this config option displayed under title
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_POPULARDSC';
// form element type used in config form for this option. can be one of either textbox, textarea, select, select_multi, yesno, group, group_multi
$modversion['config'][$i]['formtype'] = 'select';
// value type of this config option. can be one of either int, text, float, array, or other
// form type of 'group_multi', 'select_multi' must always be 'array'
// form type of 'yesno', 'group' must be always be 'int'
$modversion['config'][$i]['valuetype'] = 'int';
// the default value for this option
// ignore it if no default
// 'yesno' formtype must be either 0(no) or 1(yes)
$modversion['config'][$i]['default'] = 100;
// options to be displayed in selection preferences box
// required and valid for 'select' or 'select_multi' formtype option only
// language constants can be used for both array keys and values
$modversion['config'][$i]['options'] = array('5' => 5, '10' => 10, '50' => 50, '100' => 100, '200' => 200, '500' => 500, '1000' => 1000);
$i++;
$modversion['config'][$i]['name'] = 'newaddresses';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_NEWLINKS';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_NEWLINKSDSC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 10;
$modversion['config'][$i]['options'] = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50);
$i++;
$modversion['config'][$i]['name'] = 'perpage';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_PERPAGE';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_PERPAGEDSC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 10;
$modversion['config'][$i]['options'] = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50, _MI_MYADDRESSES_PERPAGE_ALL => 0);
$i++;
$modversion['config'][$i]['name'] = 'anonpost';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_ANONPOST';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'autoapprove';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_AUTOAPPROVE';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_AUTOAPPROVEDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
//$i++;
//$modversion['config'][$i]['name'] = 'frame';
//$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_USEFRAMES';
//$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_USEFRAMEDSC';
//$modversion['config'][$i]['formtype'] = 'yesno';
//$modversion['config'][$i]['valuetype'] = 'int';
//$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'api_key';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_API_KEY';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_API_KEYDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = "no key";
$i++;
$modversion['config'][$i]['name'] = 'default_lat';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_DEFAULT_LAT';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_DEFAULT_LATDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = "0";
$i++;
$modversion['config'][$i]['name'] = 'default_lon';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_DEFAULT_LON';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_DEFAULT_LONDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = "0";
$i++;
$modversion['config'][$i]['name'] = 'default_zoom';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_DEFAULT_ZOOM';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_DEFAULT_ZOOMDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 8;
$i++;
$modversion['config'][$i]['name'] = 'default_address';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_DEFAULT_ADDR';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_DEFAULT_ADDRDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = "";
$i++;
$modversion['config'][$i]['name'] = 'popup_options';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_POPUP_OPTIONS';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_POPUP_OPTIONSDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = "width=500,height=500,toolbar=1,location=1,directories=1,status=1,menubar=1,scrollbars=1,resizable=0,copyhistory=0";
//$i++;
//$modversion['config'][$i]['name'] = 'shotwidth';
//$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_SHOTWIDTH';
//$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_SHOTWIDTHDSC';
//$modversion['config'][$i]['formtype'] = 'textbox';
//$modversion['config'][$i]['valuetype'] = 'int';
//$modversion['config'][$i]['default'] = 470;
$i++;
$modversion['config'][$i]['name'] = 'useshots';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_USESHOTS';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_USESHOTSDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'shot_path';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_DEF_SHOT_PATH';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_DEF_SHOT_PATHDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'modules/addresses/images/shots'; // XOOPS_PATH/modules/addresses/images/shots/FIELNAME
$i++;
$modversion['config'][$i]['name'] = 'max_shot_size';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_MAX_SHOT_SIZE';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_MAX_SHOT_SIZEDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 500000; // 500000 byte
$i++;
$modversion['config'][$i]['name'] = 'max_shot_width';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_MAX_SHOT_WIDTH';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_MAX_SHOT_WIDTHDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 100; // 100 pixel
$i++;
$modversion['config'][$i]['name'] = 'max_shot_height';
$modversion['config'][$i]['title'] = '_MI_MYADDRESSES_MAX_SHOT_HEIGHT';
$modversion['config'][$i]['description'] = '_MI_MYADDRESSES_MAX_SHOT_HEIGHTDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 100; // 100 pixel

// Notification

$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'addresses_notify_iteminfo';

$modversion['notification']['category'][1]['name'] = 'global';
$modversion['notification']['category'][1]['title'] = _MI_MYADDRESSES_GLOBAL_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_MYADDRESSES_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = array('index.php','cat_view.php','address_single.php');

$modversion['notification']['category'][2]['name'] = 'category';
$modversion['notification']['category'][2]['title'] = _MI_MYADDRESSES_CATEGORY_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_MYADDRESSES_CATEGORY_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = array('cat_view.php', 'address_single.php');
$modversion['notification']['category'][2]['item_name'] = 'cid';
$modversion['notification']['category'][2]['allow_bookmark'] = 1;

$modversion['notification']['category'][3]['name'] = 'address';
$modversion['notification']['category'][3]['title'] = _MI_MYADDRESSES_LINK_NOTIFY;
$modversion['notification']['category'][3]['description'] = _MI_MYADDRESSES_LINK_NOTIFYDSC;
$modversion['notification']['category'][3]['subscribe_from'] = 'address_single.php';
$modversion['notification']['category'][3]['item_name'] = 'aid';
$modversion['notification']['category'][3]['allow_bookmark'] = 1;

$modversion['notification']['event'][1]['name'] = 'new_category';
$modversion['notification']['event'][1]['category'] = 'global';
$modversion['notification']['event'][1]['title'] = _MI_MYADDRESSES_GLOBAL_NEWCATEGORY_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_MYADDRESSES_GLOBAL_NEWCATEGORY_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_MYADDRESSES_GLOBAL_NEWCATEGORY_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'global_newcategory_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_MYADDRESSES_GLOBAL_NEWCATEGORY_NOTIFYSBJ;

$modversion['notification']['event'][2]['name'] = 'address_modify';
$modversion['notification']['event'][2]['category'] = 'global';
$modversion['notification']['event'][2]['admin_only'] = 1;
$modversion['notification']['event'][2]['title'] = _MI_MYADDRESSES_GLOBAL_LINKMODIFY_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_MYADDRESSES_GLOBAL_LINKMODIFY_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_MYADDRESSES_GLOBAL_LINKMODIFY_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'global_linkmodify_notify';
$modversion['notification']['event'][2]['mail_subject'] = _MI_MYADDRESSES_GLOBAL_LINKMODIFY_NOTIFYSBJ;

$modversion['notification']['event'][3]['name'] = 'address_broken';
$modversion['notification']['event'][3]['category'] = 'global';
$modversion['notification']['event'][3]['admin_only'] = 1;
$modversion['notification']['event'][3]['title'] = _MI_MYADDRESSES_GLOBAL_LINKBROKEN_NOTIFY;
$modversion['notification']['event'][3]['caption'] = _MI_MYADDRESSES_GLOBAL_LINKBROKEN_NOTIFYCAP;
$modversion['notification']['event'][3]['description'] = _MI_MYADDRESSES_GLOBAL_LINKBROKEN_NOTIFYDSC;
$modversion['notification']['event'][3]['mail_template'] = 'global_linkbroken_notify';
$modversion['notification']['event'][3]['mail_subject'] = _MI_MYADDRESSES_GLOBAL_LINKBROKEN_NOTIFYSBJ;

$modversion['notification']['event'][4]['name'] = 'address_submit';
$modversion['notification']['event'][4]['category'] = 'global';
$modversion['notification']['event'][4]['admin_only'] = 1;
$modversion['notification']['event'][4]['title'] = _MI_MYADDRESSES_GLOBAL_LINKSUBMIT_NOTIFY;
$modversion['notification']['event'][4]['caption'] = _MI_MYADDRESSES_GLOBAL_LINKSUBMIT_NOTIFYCAP;
$modversion['notification']['event'][4]['description'] = _MI_MYADDRESSES_GLOBAL_LINKSUBMIT_NOTIFYDSC;
$modversion['notification']['event'][4]['mail_template'] = 'global_addresssubmit_notify';
$modversion['notification']['event'][4]['mail_subject'] = _MI_MYADDRESSES_GLOBAL_LINKSUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][5]['name'] = 'new_address';
$modversion['notification']['event'][5]['category'] = 'global';
$modversion['notification']['event'][5]['title'] = _MI_MYADDRESSES_GLOBAL_NEWLINK_NOTIFY;
$modversion['notification']['event'][5]['caption'] = _MI_MYADDRESSES_GLOBAL_NEWLINK_NOTIFYCAP;
$modversion['notification']['event'][5]['description'] = _MI_MYADDRESSES_GLOBAL_NEWLINK_NOTIFYDSC;
$modversion['notification']['event'][5]['mail_template'] = 'global_newlink_notify';
$modversion['notification']['event'][5]['mail_subject'] = _MI_MYADDRESSES_GLOBAL_NEWLINK_NOTIFYSBJ;

$modversion['notification']['event'][6]['name'] = 'address_submit';
$modversion['notification']['event'][6]['category'] = 'category';
$modversion['notification']['event'][6]['admin_only'] = 1;
$modversion['notification']['event'][6]['title'] = _MI_MYADDRESSES_CATEGORY_LINKSUBMIT_NOTIFY;
$modversion['notification']['event'][6]['caption'] = _MI_MYADDRESSES_CATEGORY_LINKSUBMIT_NOTIFYCAP;
$modversion['notification']['event'][6]['description'] = _MI_MYADDRESSES_CATEGORY_LINKSUBMIT_NOTIFYDSC;
$modversion['notification']['event'][6]['mail_template'] = 'category_addresssubmit_notify';
$modversion['notification']['event'][6]['mail_subject'] = _MI_MYADDRESSES_CATEGORY_LINKSUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][7]['name'] = 'new_address';
$modversion['notification']['event'][7]['category'] = 'category';
$modversion['notification']['event'][7]['title'] = _MI_MYADDRESSES_CATEGORY_NEWLINK_NOTIFY;
$modversion['notification']['event'][7]['caption'] = _MI_MYADDRESSES_CATEGORY_NEWLINK_NOTIFYCAP;
$modversion['notification']['event'][7]['description'] = _MI_MYADDRESSES_CATEGORY_NEWLINK_NOTIFYDSC;
$modversion['notification']['event'][7]['mail_template'] = 'category_newlink_notify';
$modversion['notification']['event'][7]['mail_subject'] = _MI_MYADDRESSES_CATEGORY_NEWLINK_NOTIFYSBJ;

$modversion['notification']['event'][8]['name'] = 'approve';
$modversion['notification']['event'][8]['category'] = 'address';
$modversion['notification']['event'][8]['invisible'] = 1;
$modversion['notification']['event'][8]['title'] = _MI_MYADDRESSES_LINK_APPROVE_NOTIFY;
$modversion['notification']['event'][8]['caption'] = _MI_MYADDRESSES_LINK_APPROVE_NOTIFYCAP;
$modversion['notification']['event'][8]['description'] = _MI_MYADDRESSES_LINK_APPROVE_NOTIFYDSC;
$modversion['notification']['event'][8]['mail_template'] = 'link_approve_notify';
$modversion['notification']['event'][8]['mail_subject'] = _MI_MYADDRESSES_LINK_APPROVE_NOTIFYSBJ;
?>
